# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the 2022.1 branch
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 # Set up Python 3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    # Install sphinx and dependencies
    - name: install sphinx and dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install docutils==0.16 bs4
    - name: execute py script
     # run the run.py to get the latest data
      run: |
            cd 2021-2
            cd source
            cp ../../ftmap.py .
            echo "Hello World"
            python ftmap.py
            
        
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "$(git log --format='%ae' HEAD^!)"
        git config --local user.name "$(git log --format='%an' HEAD^!)"
        git remote add github "https://tzx0004:trump#trump1@github.com/tzx0004/Vitis-Tutorials.git"
        git pull github gh-pages --ff-only
        git add .
        if [ -z "$(git status --porcelain)" ]; then
          exit 0
        fi
        git commit -m "Fix a[href] in Webflow exported html"
        git push github HEAD:gh-pages
